# Generated by Django 4.0 on 2021-12-20 10:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('gym', '0002_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('active', 'Active'), ('inactive', 'Inactive')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='authentication.user')),
                ('programs', models.ManyToManyField(to='gym.Program')),
            ],
        ),
    ]
